In [127]:
import pandas as pd 
import numpy as np
import seaborn as sb
import matplotlib.pyplot as plt

In [128]:
df=pd.read_csv('../DataSets/Diabetes_PIMA.csv')
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [129]:
df.dtypes

Pregnancies                   int64
Glucose                       int64
BloodPressure                 int64
SkinThickness                 int64
Insulin                       int64
BMI                         float64
DiabetesPedigreeFunction    float64
Age                           int64
Outcome                       int64
dtype: object

In [130]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [131]:
df.corr()

Pregnancies   Glucose  BloodPressure  SkinThickness  \
Pregnancies                  1.000000  0.129459       0.141282      -0.081672   
Glucose                      0.129459  1.000000       0.152590       0.057328   
BloodPressure                0.141282  0.152590       1.000000       0.207371   
SkinThickness               -0.081672  0.057328       0.207371       1.000000   
Insulin                     -0.073535  0.331357       0.088933       0.436783   
BMI                          0.017683  0.221071       0.281805       0.392573   
DiabetesPedigreeFunction    -0.033523  0.137337       0.041265       0.183928   
Age                          0.544341  0.263514       0.239528      -0.113970   
Outcome                      0.221898  0.466581       0.065068       0.074752   

                           Insulin       BMI  DiabetesPedigreeFunction  \
Pregnancies              -0.073535  0.017683                 -0.033523   
Glucose                   0.331357  0.221071                  0.137337   
BloodPressure             0.088933  0.281805                  0.041265   
SkinThickness             0.436783  0.392573                  0.183928   
Insulin                   1.000000  0.197859                  0.185071   
BMI                       0.197859  1.000000                  0.140647   
DiabetesPedigreeFunction  0.185071  0.140647                  1.000000   
Age                      -0.042163  0.036242                  0.033561   
Outcome                   0.130548  0.292695                  0.173844   

                               Age   Outcome  
Pregnancies               0.544341  0.221898  
Glucose                   0.263514  0.466581  
BloodPressure             0.239528  0.065068  
SkinThickness            -0.113970  0.074752  
Insulin                  -0.042163  0.130548  
BMI                       0.036242  0.292695  
DiabetesPedigreeFunction  0.033561  0.173844  
Age                       1.000000  0.238356  
Outcome                   0.238356  1.000000

In [132]:
r=df.drop(['BloodPressure','SkinThickness'],axis=1)

In [133]:
r

Pregnancies  Glucose  Insulin   BMI  DiabetesPedigreeFunction  Age  \
0              6      148        0  33.6                     0.627   50   
1              1       85        0  26.6                     0.351   31   
2              8      183        0  23.3                     0.672   32   
3              1       89       94  28.1                     0.167   21   
4              0      137      168  43.1                     2.288   33   
..           ...      ...      ...   ...                       ...  ...   
763           10      101      180  32.9                     0.171   63   
764            2      122        0  36.8                     0.340   27   
765            5      121      112  26.2                     0.245   30   
766            1      126        0  30.1                     0.349   47   
767            1       93        0  30.4                     0.315   23   

     Outcome  
0          1  
1          0  
2          1  
3          0  
4          1  
..       ...  
763        0  
764        0  
765        0  
766        1  
767        0  

[768 rows x 7 columns]

In [134]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [135]:
x=r.drop('Outcome',axis=1).values
y=r['Outcome'].values

In [136]:
x.shape

(768, 6)

In [137]:
y.shape

(768,)

In [138]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.3)

In [139]:
xtrain.shape

(537, 6)

In [140]:
ytrain.shape

(537,)

In [141]:
model=DecisionTreeClassifier(criterion='entropy',max_features=6,min_samples_leaf=2,splitter='random',max_depth=7)
model.fit(xtrain,ytrain)

DecisionTreeClassifier(criterion='entropy', max_depth=7, max_features=6,
                       min_samples_leaf=2, splitter='random')

In [142]:
ypred=model.predict(xtest)
ypred

array([0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0], dtype=int64)

In [143]:
acc=accuracy_score(ypred,ytest)
acc*100

69.26406926406926

In [144]:
cm=confusion_matrix(ypred,ytest)
cm

array([[128,  52],
       [ 19,  32]], dtype=int64)

In [145]:
from sklearn.model_selection import cross_val_score,KFold

In [146]:
modelCV=DecisionTreeClassifier()

In [147]:
scoring='accuracy'

In [148]:
kfold=KFold(n_splits=15)
kfold

KFold(n_splits=15, random_state=None, shuffle=False)

In [149]:
score=cross_val_score(modelCV,x,y,cv=10,scoring='accuracy')
score

array([0.72727273, 0.74025974, 0.72727273, 0.64935065, 0.74025974,
       0.64935065, 0.76623377, 0.79220779, 0.65789474, 0.73684211])

In [150]:
score.mean()*100

71.86944634313055